### ISSUE TITLE
Can't push my modifications with the lib

### ISSUE THREAD

**Issue by k0pernicus** [alexcrichton/git2-rs#103]
Hi there!

I try to push some modifications on a remote with this part of code:
```
let mut callbacks = RemoteCallbacks::new();
callbacks.credentials(|user, pass, ctype| {
    return Cred::userpass_plaintext(user, pass.unwrap());
});
let mut push_options = PushOptions::new();
push_options.remote_callbacks(callbacks);
match r_remote.push(&[], Some(&mut push_options)) {
    Ok(_) => println!("Branch has been pushed!"),
    Err(error) => println!("Error {}", error),
};
```

but I obtained the error

```
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
thread '<main>' panicked at 'callback has panicked, and continuing to unwind into C is not safe, so aborting the process', /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/git2-0.3.3/src/panic.rs:59
stack backtrace:
   1:     0x5620f8d584a0 - sys::backtrace::tracing::imp::write::haa19c02b4de52f3bG0t
   2:     0x5620f8d5a7f5 - panicking::log_panic::_<closure>::closure.41218
   3:     0x5620f8d5a270 - panicking::log_panic::h527fe484e9de8fe1W7x
   4:     0x5620f8d4c478 - sys_common::unwind::begin_unwind_inner::h51f64b1a34c60827fTs
   5:     0x5620f8ca4be7 - sys_common::unwind::begin_unwind::begin_unwind::h16792344233475443377
                        at ../src/libstd/sys/common/unwind/mod.rs:237
   6:     0x5620f8ca4b61 - panic::wrap::_<impl>::drop::h134a97ebfc9ce0d4a3b
                        at /home/antonin/Documents/dev/giwyn-rs/<std macros>:3
   7:     0x5620f8ca8eac - panic..wrap..Bomb::drop.22242::h43c09561fd975edb
   8:     0x5620f8cb245a - panic::wrap::h61232809709193426
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/git2-0.3.3/src/panic.rs:68
   9:     0x5620f8cb216c - remote_callbacks::credentials_cb::__rust_abi
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/git2-0.3.3/src/panic.rs:23
  10:     0x5620f8cb1f32 - remote_callbacks::credentials_cb::h8908a538de8f4e66gli
  11:     0x5620f8d2650a - on_headers_complete
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/transports/http.c:354
  12:     0x5620f8d2c420 - http_parser_execute
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/deps/http-parser/http_parser.c:1579
  13:     0x5620f8d2720e - http_stream_read
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/transports/http.c:707
  14:     0x5620f8d2463a - git_smart__recv_cb
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/transports/smart.c:22
  15:     0x5620f8d2dd6d - gitno_recv
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/netops.c:20
  16:     0x5620f8d30279 - git_smart__store_refs
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/transports/smart_protocol.c:50
  17:     0x5620f8d24dc9 - git_smart__connect
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/transports/smart.c:242
  18:     0x5620f8cc1d91 - git_remote_connect
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/remote.c:740
  19:     0x5620f8cc3d99 - git_remote_push
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/libgit2-sys-0.3.8/libgit2/src/remote.c:2464
  20:     0x5620f8cb142c - remote::_<impl>::push::h32e67b0670fb3884XTh
                        at /home/antonin/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/git2-0.3.3/src/call.rs:14
  21:     0x5620f8c4c5b7 - interactive_mod::_<impl>::create_back_up_for_good_repositories::h97af815ae4d95cd22Fa
                        at src/interactive_mod.rs:251
  22:     0x5620f8c4da58 - interactive_mod::_<impl>::trigger_format_process::he78dc6105ad60c163Qa
                        at src/interactive_mod.rs:264
  23:     0x5620f8c3be3c - interactive_mod::_<impl>::run::h62d33ec07166d347fRa
                        at src/interactive_mod.rs:293
  24:     0x5620f8c2fb50 - main::h2f511758d082d7d51Va
                        at src/main.rs:131
  25:     0x5620f8d5a014 - sys_common::unwind::try::try_fn::h11901883998771707766
  26:     0x5620f8d57948 - __rust_try
  27:     0x5620f8d59cb6 - rt::lang_start::hc150f651dd2af18b44x
  28:     0x5620f8c3c5c9 - main
  29:     0x7fdebfc08ec4 - __libc_start_main
  30:     0x5620f8c2e388 - <unknown>
  31:                0x0 - <unknown>
thread panicked while panicking. aborting.An unknown error occurred
```

I tried several solutions (found in the "Issues" section here), but no one works currently...

Have you ever found this error in a code?

**Comment by alexcrichton** [comment]
It looks like the problem here is that the `pass` variable passed in is `None` and you're calling `.unwrap()`. I believe this is just the password encoded in the URL, and it will be `None` if there wasn't one. If you use `.unwrap_or(...)` with a default password (or one learned from elsewhere), I think that'd do the trick!

**Comment by k0pernicus** [comment]
Sorry for the delay.
I've update my code, and the program seems to loop...

This is my code:
```
match branch_back_up.as_mut() {
    Ok(branch) => match branch.set_upstream(Some("back_up")) {
        Ok(_) => println!("Branch 'back_up' has been updated!"),
        Err(error) => println!("Error due to {}", error),
    },
    Err(error) => panic!("Canno't upstream the branch 'back_up', due to error {}", error),
}
let refname = match branch_back_up.as_mut() {
    Ok(branch) => branch.get(),
    Err(error) => panic!("ERROR: {}", error),
};
// Find remote
let mut r_remote = r.find_remote("origin").unwrap();
// Push branch
let mut callbacks = RemoteCallbacks::new();
callbacks.credentials(|user, pass, ctype| {
    return Cred::userpass_plaintext(user, pass.unwrap_or("MY_PASSWORD"));
});
let mut push_options = PushOptions::new();
push_options.remote_callbacks(callbacks);
match r_remote.push(&[], Some(&mut push_options)) {
    Ok(_) => println!("Branch has been pushed!"),
    Err(error) => println!("Error {}", error),
};
```
but, since less 10 minutes, the program is blocked on
```
README.md has been added!
Branch 'back_up' has been updated!
```

Did I missed something? :-/

**Comment by alexcrichton** [comment]
I think that you may have to specify some refs of what to push? I always forget what you precisely need to pass in, but it may help to [see a working code example as well](https://github.com/rust-lang/crates.io/blob/02029a3785edf81da0ab1c88ebab0d4d4cf2cd36/src/git.rs#L105-L158), although that doesn't deal with branches much as it only works with the `master` branch
