### ISSUE TITLE
Build fails with LibreSSL when built as a dependency

### ISSUE THREAD

**Issue by ibabushkin** [alexcrichton/git2-rs#317]
I am hitting odd build failures, that I can't seem to diagnose properly.
The following compiles without any error:
```sh
$ git checkout libgit2-sys-0.7.1
$ cargo build
```

However, when I build `cargo`, I get the following message:
```sh
$ cargo build
[...]
error: failed to run custom build command for `libgit2-sys v0.7.1`
process didn't exit successfully: `/home/twk/src/clones/cargo/target/debug/build/libgit2-sys-ae220773f7e720dd/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_CLAR=OFF" "-DCMAKE_INSTALL_PREFIX=/home/twk/src/clones/cargo/target/debug/build/libgit2-sys-3e8a6c13883d376e/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Success
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Performing Test IS_WALL_SUPPORTED
-- Performing Test IS_WALL_SUPPORTED - Success
-- Performing Test IS_WEXTRA_SUPPORTED
-- Performing Test IS_WEXTRA_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Success
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Looking for regcomp_l
-- Looking for regcomp_l - not found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Checking for module 'libcurl'
--   Found libcurl, version 7.60.0
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "2.0.0") 
-- Found HTTP_Parser: /usr/include  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Checking for module 'libssh2'
--   Found libssh2, version 1.8.0
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - found
-- Enabled features:
 * threadsafe, threadsafe support
 * cURL, cURL for HTTP proxy support
 * HTTPS, using OpenSSL
 * SHA, using CollisionDetection
 * http-parser, http-parser support
 * zlib, using system zlib
 * SSH, SSH transport support

-- Disabled features:
 * debugpool, debug pool allocator
 * tracing, tracing support
 * SPNEGO, SPNEGO authentication support
 * iconv, iconv encoding conversion support

-- Configuring done
-- Generating done
-- Build files have been written to: /home/twk/src/clones/cargo/target/debug/build/libgit2-sys-3e8a6c13883d376e/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
Scanning dependencies of target git2internal
[  1%] Building C object src/CMakeFiles/git2internal.dir/annotated_commit.c.o
[  2%] Building C object src/CMakeFiles/git2internal.dir/apply.c.o
[  2%] Building C object src/CMakeFiles/git2internal.dir/attr.c.o
[  3%] Building C object src/CMakeFiles/git2internal.dir/attr_file.c.o
[  4%] Building C object src/CMakeFiles/git2internal.dir/attrcache.c.o
[  4%] Building C object src/CMakeFiles/git2internal.dir/blame.c.o
[  5%] Building C object src/CMakeFiles/git2internal.dir/blame_git.c.o
[  6%] Building C object src/CMakeFiles/git2internal.dir/blob.c.o
[  6%] Building C object src/CMakeFiles/git2internal.dir/branch.c.o
[  7%] Building C object src/CMakeFiles/git2internal.dir/buf_text.c.o
[  8%] Building C object src/CMakeFiles/git2internal.dir/buffer.c.o
[  8%] Building C object src/CMakeFiles/git2internal.dir/cache.c.o
[  9%] Building C object src/CMakeFiles/git2internal.dir/checkout.c.o
[ 10%] Building C object src/CMakeFiles/git2internal.dir/cherrypick.c.o
[ 11%] Building C object src/CMakeFiles/git2internal.dir/clone.c.o
[ 11%] Building C object src/CMakeFiles/git2internal.dir/commit.c.o
[ 12%] Building C object src/CMakeFiles/git2internal.dir/commit_list.c.o
[ 13%] Building C object src/CMakeFiles/git2internal.dir/config.c.o
[ 13%] Building C object src/CMakeFiles/git2internal.dir/config_cache.c.o
[ 14%] Building C object src/CMakeFiles/git2internal.dir/config_file.c.o
[ 15%] Building C object src/CMakeFiles/git2internal.dir/config_parse.c.o
[ 15%] Building C object src/CMakeFiles/git2internal.dir/crlf.c.o
[ 16%] Building C object src/CMakeFiles/git2internal.dir/date.c.o
[ 17%] Building C object src/CMakeFiles/git2internal.dir/delta.c.o
[ 17%] Building C object src/CMakeFiles/git2internal.dir/describe.c.o
[ 18%] Building C object src/CMakeFiles/git2internal.dir/diff.c.o
[ 19%] Building C object src/CMakeFiles/git2internal.dir/diff_driver.c.o
[ 20%] Building C object src/CMakeFiles/git2internal.dir/diff_file.c.o
[ 20%] Building C object src/CMakeFiles/git2internal.dir/diff_generate.c.o
[ 21%] Building C object src/CMakeFiles/git2internal.dir/diff_parse.c.o
[ 22%] Building C object src/CMakeFiles/git2internal.dir/diff_print.c.o
[ 22%] Building C object src/CMakeFiles/git2internal.dir/diff_stats.c.o
[ 23%] Building C object src/CMakeFiles/git2internal.dir/diff_tform.c.o
[ 24%] Building C object src/CMakeFiles/git2internal.dir/diff_xdiff.c.o
[ 24%] Building C object src/CMakeFiles/git2internal.dir/errors.c.o
[ 25%] Building C object src/CMakeFiles/git2internal.dir/fetch.c.o
[ 26%] Building C object src/CMakeFiles/git2internal.dir/fetchhead.c.o
[ 26%] Building C object src/CMakeFiles/git2internal.dir/filebuf.c.o
[ 27%] Building C object src/CMakeFiles/git2internal.dir/fileops.c.o
[ 28%] Building C object src/CMakeFiles/git2internal.dir/filter.c.o
[ 28%] Building C object src/CMakeFiles/git2internal.dir/fnmatch.c.o
[ 29%] Building C object src/CMakeFiles/git2internal.dir/global.c.o
[ 30%] Building C object src/CMakeFiles/git2internal.dir/graph.c.o

--- stderr
fatal: not a git repository (or any of the parent directories): .git
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_CXX_FLAGS


In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:36:25: error: static declaration of 'BIO_meth_new' follows non-static declaration
GIT_INLINE(BIO_METHOD*) BIO_meth_new(int type, const char *name)
                        ^
/usr/include/openssl/bio.h:338:13: note: previous declaration is here
BIO_METHOD *BIO_meth_new(int type, const char *name);
            ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:49:18: error: static declaration of 'BIO_meth_free' follows non-static declaration
GIT_INLINE(void) BIO_meth_free(BIO_METHOD *biom)
                 ^
/usr/include/openssl/bio.h:339:6: note: previous declaration is here
void BIO_meth_free(BIO_METHOD *biom);
     ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:54:17: error: static declaration of 'BIO_meth_set_write' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_write(BIO_METHOD *biom, int (*write) (BIO *, const char *, int))
                ^
/usr/include/openssl/bio.h:341:5: note: previous declaration is here
int BIO_meth_set_write(BIO_METHOD *biom,
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:60:17: error: static declaration of 'BIO_meth_set_read' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_read(BIO_METHOD *biom, int (*read) (BIO *, char *, int))
                ^
/usr/include/openssl/bio.h:344:5: note: previous declaration is here
int BIO_meth_set_read(BIO_METHOD *biom, int (*read)(BIO *, char *, int));
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:66:17: error: static declaration of 'BIO_meth_set_puts' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_puts(BIO_METHOD *biom, int (*puts) (BIO *, const char *))
                ^
/usr/include/openssl/bio.h:346:5: note: previous declaration is here
int BIO_meth_set_puts(BIO_METHOD *biom, int (*puts)(BIO *, const char *));
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:72:17: error: static declaration of 'BIO_meth_set_gets' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_gets(BIO_METHOD *biom, int (*gets) (BIO *, char *, int))
                ^
/usr/include/openssl/bio.h:348:5: note: previous declaration is here
int BIO_meth_set_gets(BIO_METHOD *biom, int (*gets)(BIO *, char *, int));
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:79:17: error: static declaration of 'BIO_meth_set_ctrl' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_ctrl(BIO_METHOD *biom, long (*ctrl) (BIO *, int, long, void *))
                ^
/usr/include/openssl/bio.h:350:5: note: previous declaration is here
int BIO_meth_set_ctrl(BIO_METHOD *biom, long (*ctrl)(BIO *, int, long, void *));
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:85:17: error: static declaration of 'BIO_meth_set_create' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_create(BIO_METHOD *biom, int (*create) (BIO *))
                ^
/usr/include/openssl/bio.h:352:5: note: previous declaration is here
int BIO_meth_set_create(BIO_METHOD *biom, int (*create)(BIO *));
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:91:17: error: static declaration of 'BIO_meth_set_destroy' follows non-static declaration
GIT_INLINE(int) BIO_meth_set_destroy(BIO_METHOD *biom, int (*destroy) (BIO *))
                ^
/usr/include/openssl/bio.h:354:5: note: previous declaration is here
int BIO_meth_set_destroy(BIO_METHOD *biom, int (*destroy)(BIO *));
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:97:17: error: static declaration of 'BIO_get_new_index' follows non-static declaration
GIT_INLINE(int) BIO_get_new_index(void)
                ^
/usr/include/openssl/bio.h:599:5: note: previous declaration is here
int BIO_get_new_index(void);
    ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:103:18: error: static declaration of 'BIO_set_init' follows non-static declaration
GIT_INLINE(void) BIO_set_init(BIO *b, int init)
                 ^
/usr/include/openssl/bio.h:610:7: note: previous declaration is here
void    BIO_set_init(BIO *a, int init);
        ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:108:18: error: static declaration of 'BIO_set_data' follows non-static declaration
GIT_INLINE(void) BIO_set_data(BIO *a, void *ptr)
                 ^
/usr/include/openssl/bio.h:609:7: note: previous declaration is here
void    BIO_set_data(BIO *a, void *ptr);
        ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:113:19: error: static declaration of 'BIO_get_data' follows non-static declaration
GIT_INLINE(void*) BIO_get_data(BIO *a)
                  ^
/usr/include/openssl/bio.h:608:8: note: previous declaration is here
void    *BIO_get_data(BIO *a);
         ^
In file included from /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/global.c:14:
/home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.7.1/libgit2/src/streams/openssl.h:118:35: error: static declaration of 'ASN1_STRING_get0_data' follows non-static declaration
GIT_INLINE(const unsigned char *) ASN1_STRING_get0_data(const ASN1_STRING *x)
                                  ^
/usr/include/openssl/asn1.h:788:22: note: previous declaration is here
const unsigned char *ASN1_STRING_get0_data(const ASN1_STRING *x);
                     ^
14 errors generated.
make[2]: *** [src/CMakeFiles/git2internal.dir/build.make:596: src/CMakeFiles/git2internal.dir/global.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:125: src/CMakeFiles/git2internal.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:632:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: cmake::fail
             at /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:632
   7: cmake::run
             at /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:613
   8: cmake::Config::build
             at /home/twk/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:520
   9: build_script_build::main
             at ./build.rs:128
  10: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  15: main
  16: __libc_start_main
             at ../csu/libc-start.c:308
  17: _start
             at ../sysdeps/x86_64/start.S:120
```

The system in question runs LibreSSL 2.7.3.
I'm not sure how I could gather any more useful info, as I can't imagine the source of the problem without being able to isolate it properly -- the C compiler's output doesn't point at anything trivial either.

**Comment by alexcrichton** [comment]
It looks like this may be a libgit2 build issue?

**Comment by ibabushkin** [comment]
Hm, do you have any idea why it happens only when built as a dependency?

**Comment by heirecka** [comment]
This is fixed upstream in https://github.com/libgit2/libgit2/commit/7490d449b518115a1ae86b01397e95c38e39cff1
So it should vanish when the libgit2 submodule moves from c9d59c6 to a commit beyond 7490d44

**Comment by alexcrichton** [comment]
Awesome! I think all we'll need here is a PR to update the submodule now!

**Comment by ibabushkin** [comment]
Alright, issue is fixed. Thanks everyone!
