### ISSUE TITLE
Utf8Error for not exists git repository domain on Windows 10

### ISSUE THREAD

**Issue by ondj** [alexcrichton/git2-rs#324]
Running this mininal code with not exists domain on Czech Windows 10 panics with error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 57, error_len: Some(1) }', libcore\result.rs:945:5
```

```rust
extern crate git2;

use git2::Repository;

fn main() {
    let url = "ssh://git@not-exists-domain.test/test";
    let repo = match Repository::clone(url, "clone") {
        Ok(repo) => repo,
        Err(e) => panic!("failed to clone: {}", e),
    };
}
```

Important part of backtrace:

```
 8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
 9: core::result::unwrap_failed<core::str::Utf8Error>
           at C:\projects\rust\src\libcore\macros.rs:26
10: core::result::Result<str*, core::str::Utf8Error>::unwrap<str*,core::str::Utf8Error>
           at C:\projects\rust\src\libcore\result.rs:782
11: git2::error::Error::from_raw
           at C:\Users\ondj\.cargo\registry\src\github.com-1ecc6299db9ec823\git2-0.7.1\src\error.rs:61
12: git2::error::Error::last_error
           at C:\Users\ondj\.cargo\registry\src\github.com-1ecc6299db9ec823\git2-0.7.1\src\error.rs:52
13: git2::call::last_error
           at C:\Users\ondj\.cargo\registry\src\github.com-1ecc6299db9ec823\git2-0.7.1\src\call.rs:48
14: git2::call::try
           at C:\Users\ondj\.cargo\registry\src\github.com-1ecc6299db9ec823\git2-0.7.1\src\call.rs:40
15: git2::build::RepoBuilder::clone
           at C:\Users\ondj\.cargo\registry\src\github.com-1ecc6299db9ec823\git2-0.7.1\src\build.rs:231
16: git2::repo::Repository::clone<str*>
           at C:\Users\ondj\.cargo\registry\src\github.com-1ecc6299db9ec823\git2-0.7.1\src\repo.rs:196
17: cargo_ssh::main
```

First reported as https://github.com/rust-lang/cargo/issues/5681

**Comment by ondj** [comment]
This problem was solved, but now the error message looks like this:

```
thread 'main' panicked at 'failed to clone: failed to resolve address for not-exists-domain.test: Nen� zn�m ��dn� takov� hostitel. ; class=Net (12)', src\main.rs:9:19
```

I think that the problem is that Windows return error strings in UTF-16 and not in UTF-8. See for example https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/os.rs#L76

**Comment by alexcrichton** [comment]
Hm so these error messages are coming from libgit2 and AFAIK libgit2 should be giving utf-8 or ascii strings, not utf-16. This may be a bug with libgit2?
